// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9GFFsc-7bWkG6IMToBmxmY_dtpaKMALo',
    appId: '1:838842418244:web:0db0faf7aee5bf9246a811',
    messagingSenderId: '838842418244',
    projectId: 'wordapp-f41f9',
    authDomain: 'wordapp-f41f9.firebaseapp.com',
    storageBucket: 'wordapp-f41f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHvPW_nEHVYA1hLiL-rLhiCciozY_gjdk',
    appId: '1:838842418244:android:4e3f59f303d211d646a811',
    messagingSenderId: '838842418244',
    projectId: 'wordapp-f41f9',
    storageBucket: 'wordapp-f41f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyIV3fq7HnoGqWvIecVR-wzaDxJJE2LLI',
    appId: '1:838842418244:ios:69b06e21282e309d46a811',
    messagingSenderId: '838842418244',
    projectId: 'wordapp-f41f9',
    storageBucket: 'wordapp-f41f9.appspot.com',
    iosBundleId: 'com.example.wordapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyIV3fq7HnoGqWvIecVR-wzaDxJJE2LLI',
    appId: '1:838842418244:ios:66b93efbac130e6446a811',
    messagingSenderId: '838842418244',
    projectId: 'wordapp-f41f9',
    storageBucket: 'wordapp-f41f9.appspot.com',
    iosBundleId: 'com.example.wordapp.RunnerTests',
  );
}
